- name: Add an apt signing key for Kubernetesn
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ master_node }}
  when: "'kubernetesmaster' in group_names"

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

#- name: kube-apiserver.yaml
#  stat:
#    path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
#  register: register_name
#
#- name: Initialize the Kubernetes cluster using kubeadm
#  command: kubeadm init --apiserver-advertise-address="10.244.0.0/16"
#  when: 'kubernetesmaster' in group_names and not register_name.stat.exists
#
#- name: Setup kubeconfig for vagrant user
#  command: "{{ item }}"
#  with_items:
#    - mkdir -p /home/vagrant/.kube
#    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
#    - chown vagrant:vagrant /home/vagrant/.kube/config