- debug:
    msg:  "{{ master_ip }}"
  run_once: yes

- name: Ansible insert a line before example
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ master_ip }}  kube-api.local"
  when: master == "no"

#- name: join node
#  script: "join.sh {{ kube_token }} {{ token_cert_hash }}"
#  when: master == "no"