- name: install-kubelet.yml
  include: install-kubelet.yml

- name: master-configs.yml
  include: master-configs.yml
  when: master == "yes"

- name: join-nodes.yml
  include: join-nodes.yml.yml
  when: master == "no"