- name: kube-apiserver.yaml
  stat:
    path: "/etc/kubernetes/pki/"
  register: register_name

- debug:
    msg: "{{ register_name.stat.exists }}"

- name: Initialize the Kubernetes cluster using kubeadm
  command: "sudo kubeadm init"
  delegate_to: "k8s-master-01"
  when: "not register_name.stat.exists"

- name: Setup kubeconfig for vagrant user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: '0644'
    remote_src: yes