apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name_space }}
  namespace: {{ .Values.name_space }}
  labels:
    app: {{ .Values.name_space }}
spec:
  type: {{ .Values.service_type }}
  selector:
    app: {{ .Values.name_space }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.node_port }}