# ansible-playbook -i local_files/inventory ansible/playbooks/site.yml
---
- hosts: kubernetescluster
  become: true
  any_errors_fatal: true
  vars_files:
    - "../../local_files/ansible_local_vars.yml"
    - "kubernetes_version_vars.yml"
  roles:
    - pub-key
    - update-linux
    - install-containerd
    - bootstrap-kubernetes
    - kubernetes-upgrade-diagnostics
    - kubernetes-upgrade

  post_tasks:
    - name: Get kube config file
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        flat: yes
      when: inventory_hostname in groups['master']

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Run kubectl get nodes
      become: false
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"
      command: kubectl get nodes
      register: command_output

    - debug:
        var: command_output.stdout_lines
