---
- hosts: kubernetescluster
  become: true
  vars_files:
    - "../../local_files/ansible_extra_vars.yml"
  pre_tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - debug:
      msg: "{{ specific_node }}"
  roles:
    - { role: install-docker, when: "'kubernetesmaster' in group_names" }
    - { role: install-kubectl, when: "'kubernetesmaster' in group_names" }
