# ansible-playbook -i local_files/inventory ansible/playbooks/test-connection.yml
# Run separately for individual servers as follows
---
- name: configs
  become: true
  gather_facts: no
  hosts: kubernetes-cluster
  ignore_unreachable: yes
  vars:
    ENV: "esxi"
  vars_prompt:
    - name: SHUTDOWN
      prompt: Shutdown yes/no
      private: no
  roles:
    - ping_role