pip: "/virtual-python/shims/pip"
python: "/virtual-python/shims/python"
circleci_version: "0.1.16535"
circleci_url: "https://github.com/CircleCI-Public/circleci-cli/releases/download/v{{ circleci_version }}/circleci-cli_{{ circleci_version }}_linux_amd64.tar.gz"

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git-core
  - gcc
  - make
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libffi-dev
  - cifs-utils
  - autofs
  - zip
  - unzip

users:
  - circleci